name: waste-classifier
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision>=0.15.0
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-learn>=1.3.0
  - pillow>=10.0.0
  - pip:
      - Flask>=2.3.0
      - Werkzeug>=2.3.0
      - opencv-python>=4.8.0
      - gradio
      - onnyxruntime
